language: clojure
dist: xenial

install:
    # install clj
    - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
    - chmod +x linux-install-1.10.1.466.sh
    - sudo ./linux-install-1.10.1.466.sh

    # needed to properly render images (in tables)
    - sudo pip install pandocfilters
    - sudo apt-get install librsvg2-dev

    - npm ci

script:
    - npm run test

after_success:
    # build if on the master branch (in prep for deploy)
    - if [ "$TRAVIS_BRANCH" = master ] && [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then npm run build:ci || travis_terminate 1; fi

cache:
    directories:
        - $HOME/.m2

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_DEPLOY # Set in travis-ci.org dashboard
    local_dir: web/public
    on:
        branch: master


