#!/bin/bash

# download a pre-built version of pandoc for travis
wget -q https://github.com/yihui/travis-bin/raw/gh-pages/pandoc.tar.gz
tar xzvf pandoc.tar.gz
mkdir -p ~/.local/bin
mv pandoc ~/.local/bin/

pandoc --version

# install pdflatex
sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng

pdflatex --version

(cd compiler && clojure -A:build) || exit 1
(cd web && npm run build) || exit 1
