#!/bin/bash

# download a pre-built version of pandoc for travis
wget -q https://github.com/yihui/travis-bin/raw/gh-pages/pandoc.tar.gz
tar xzvf pandoc.tar.gz
mkdir -p ~/.local/bin
mv pandoc ~/.local/bin/

pandoc --version

# install pdflatex
sudo apt-get -qq update
sudo apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra lmodern

pdflatex --version

# finally, compile our assets
(cd compiler && clojure -A:build) || exit 1
(cd web && npm run build:gh-pages) || exit 1

# prepare for publishing if on travis
if [ "$TRAVIS_BRANCH" = master ]
then
    sed -i 's|/js/main.js|/vtolvr-handbook/js/main.js|' web/public/index.html
fi
